export {
  createTestContext,
  createWritableCapture,
  mockPrompts,
  normalizeError,
  runCommand,
  runHandler,
  runMiddleware,
  runTestCli,
  setArgv,
  setupTestLifecycle,
  stripAnsi,
} from '@kidd-cli/core/test'
export type {
  CommandResult,
  HandlerResult,
  MiddlewareResult,
  PromptResponses,
  RunCommandOptions,
  RunHandlerOptions,
  RunMiddlewareOptions,
  TestContextOptions,
  TestContextResult,
  TestLifecycle,
  WritableCapture,
} from '@kidd-cli/core/test'
